# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master

jobs:
- job: ExportToGitHub
  displayName: Export to GitHub
  steps:
    - checkout: none

    # Mirror clone the Azure DevOps repository
    - script: |
        git clone --mirror https://$(System.AccessToken)@dev.azure.com/DaisyOrg/Test%20Projects/_git/Test_Shipping_to_Github repo-mirror
        cd repo-mirror
      env:
        System.AccessToken: $(System.AccessToken)
      displayName: "Mirror clone from Azure DevOps"

    # Set up Git to authenticate with GitHub
    - script: |
        cd repo-mirror
        git remote set-url --push origin https://AruseyDaisy:$(GITHUB_TOKEN)@github.com/FacultyUpskillingOrg/Push_ADO_Repo_TO_GitHub.git
        git push --mirror
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)
      displayName: "Push mirror to GitHub"
