# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - none

jobs:
- job: ExportToGitHub
  displayName: Export to GitHub
  steps:
    - checkout: none

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          
          # Write your PowerShell commands here.
          Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
          Write-Host ' reflect Azure Devops repo changes to GitHub repo'
          Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '
          $stageDir = '$(Build.SourcesDirectory)' | Split-Path
          $githubDir = $stageDir +"\"+"gitHub"
          $destination = $githubDir +"\"+"Test_Shipping_to_Github.git"
          #please provide your username
          $alias = 'AruseyDaisy:'+ "$(Github.PAT)"
          #Please make sure, you remove https from azure-repo-clone-url
          $sourceURL = 'https://$(System.AccessToken)@DaisyOrg@dev.azure.com/DaisyOrg/Test%20Projects/_git/Test_Shipping_to_Github'
          #Please make sure, you remove https from github-repo-clone-url
          $destURL = 'https://' + $alias + '@github.com/FacultyUpskillingOrg/Push_ADO_Repo_TO_GitHub.git'
          #Check if the parent directory exists and delete
          if((Test-Path -path $githubDir))
          {
            Remove-Item -Path $githubDir -Recurse -force
          }
          if(!(Test-Path -path $githubDir))
          {
            New-Item -ItemType directory -Path $githubDir
            Set-Location $githubDir
            git clone --mirror $sourceURL
          }
          else
          {
            Write-Host "The given folder path $githubDir already exists";
          }
          Set-Location $destination
          Write-Output '*****Git removing remote secondary****'
          git remote rm secondary
          Write-Output '*****Git remote add****'
          git remote add --mirror=fetch secondary $destURL
          Write-Output '*****Git fetch origin****'
          git fetch $sourceURL
          Write-Output '*****Git push secondary****'
          git push secondary --all
          Write-Output '**Azure Devops repo synced with Github repo**'
          Set-Location $stageDir
          if((Test-Path -path $githubDir))
          {
           Remove-Item -Path $githubDir -Recurse -force
          }
